### ISSUE TITLE
Create Shopping List

### ISSUE THREAD

**Issue by maxilukowski** [maxilukowski/capstone-project#2]
### Value statement
As a User
I need to add items to a list and have them displayed
so that i dont forget them

### Description
![image](https://user-images.githubusercontent.com/65217230/86227081-d913f200-bb8c-11ea-80a7-e43190fabe2c.png)

- A inputfield in the headercomponent with a submit functionallity

- The added Item will be displayed in an unordered list in the body of the page

### Acceptance criteria

- [x] Basic layout (spacing / fontsize )
- [x] Added list items should be attatched at the top of the list
- [x] The page has to be scrollable in case there are many items
- [x] There should appear checkboxes to the right of the added item

### Tasks
- [x] Create feature branch
- [x] Create button and input component in Storybook
- [ ] Write component test
- [x] Add component to app
- [x] Add styles

### Size

small
