### ISSUE TITLE
check and relocate listitem

### ISSUE THREAD

**Issue by maxilukowski** [maxilukowski/capstone-project#3]
### Value statement
As a User
I need to check items and have them displayed at the bottom of the screen
so that i see which ones are no longer required

### Description
![check and relocate listitem](https://user-images.githubusercontent.com/65217230/86345189-81908780-bc5b-11ea-9c91-13cc25b1c504.png)

### Acceptance criteria

- [x] the two seperate lists (checked & unchecked) should not collide

- [x] checked items have a lower opacity

- [x] reclicking checked items should disappear & reapper in the upper list

### Tasks 

- [x] Add list component in Storybook and App

- [x] Write onClick function so items swap to the other list

- [x] Write component test 
- [x] Add styles

### Size

medium
