### ISSUE TITLE
sidebar with "add list function" + togglebutton

### ISSUE THREAD

**Issue by maxilukowski** [maxilukowski/capstone-project#5]
### Value statement
as a user
i want to see different features in a sidebar which i can toggle
so i see these options only if i want to

### Description
![Sidebar+Toggler](https://user-images.githubusercontent.com/65217230/86366501-253d6000-bc7b-11ea-9757-370961f93122.jpg)

### Acceptance criteria

- [ ] sidebar should be togglable

- [ ] by clicking on add list a inputfield should appear in which i can type in the listname

- [ ] created lists should appear in the lower part of the sidebar. by clicking on one the user will be redirected to that list and the sidebar closes itself. that way the user can switch between different list in the sidebar.

### Tasks

- [ ] add sidebar to Storybook and App

- [ ] write component test

- [ ] implement routes

- [ ] separate storage for each individual shopping list

### Size
medium
